<<<<<<< HEAD
CREATE DATABASE susbank;
USE susbank;

CREATE TABLE `usuarios` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) DEFAULT NULL,
  `correo` VARCHAR(50) DEFAULT NULL,
  `pass` VARCHAR (20) DEFAULT NULL,
  `curp` VARCHAR(20) DEFAULT NULL,
  `cel` INT(10) DEFAULT NULL,
  `num_tarjeta` VARCHAR (16) DEFAULT NULL,
  `saldo` INT (8) DEFAULT NULL,
  `clabe` VARCHAR (18) DEFAULT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `transferencia`(
 `id` INT (12) NOT NULL AUTO_INCREMENT,
 `folio` VARCHAR (5) DEFAULT NULL,
 `clabe` VARCHAR(18) DEFAULT NULL,
 `clabe_env` VARCHAR(18) DEFAULT NULL,
 `monto` INT(8) DEFAULT NULL,
 `fecha` DATETIME,
  PRIMARY KEY(`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

	

=======
CREATE DATABASE susbank;
USE susbank;

CREATE TABLE `usuarios` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) DEFAULT NULL,
  `correo` VARCHAR(50) DEFAULT NULL,
  `pass` VARCHAR (20) DEFAULT NULL,
  `curp` VARCHAR(20) DEFAULT NULL,
  `cel` INT(10) DEFAULT NULL,
  `num_tarjeta` VARCHAR (16) DEFAULT NULL,
  `saldo` INT (8) DEFAULT NULL,
  `clabe` VARCHAR (18) DEFAULT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `transferencia`(
 `id` INT (12) NOT NULL AUTO_INCREMENT,
 `folio` VARCHAR (5) DEFAULT NULL,
 `clabe` VARCHAR(18) DEFAULT NULL,
 `clabe_env` VARCHAR(18) DEFAULT NULL,
 `monto` INT(8) DEFAULT NULL,
 `fecha` DATETIME,
  PRIMARY KEY(`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

	

>>>>>>> 808b9d5444bc9176c6ff9f99d86211fe06e31d21
