function privacidad(){
    Swal.fire({
      title: 'Aviso de Privacidad',
      html:`<img src="../img/privacy-policy-animate.svg" type="img/svg" style="width:50%"/>
      <p>En cumplimiento con lo establecido en los artículos 15 y 16 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en adelante, la “Ley”) SUSBANK (en adelante, la “Responsable” o “SUSBANK”) con domicilio en Prado Norte 235 Oficina 13, Lomas de Chapultepec III Sección, Miguel Hidalgo, 11000, Ciudad de México, le informa que el presente Aviso de Privacidad (en adelante, el “Aviso”) está dirigido a los usuarios de SUSBANK (en adelante “Usuario” o “Usuarios.”)El presente documento busca informar a los Usuarios de la plataforma o aplicación móvil de SUSBANK (en adelante, la “Plataforma”), sobre la utilización y tratamiento de la información personal (en adelante, “Datos Personales”) que se recopile o genere a través de las visitas a la Plataforma, así como de los Datos Personales que el Usuario entregue y/o suministre de manera voluntaria a SUSBANK por cualquier medio diverso, o que se generen indirectamente por el uso de la Plataforma. En el primer acceso a la Plataforma, el Usuario debe leer este Aviso de Privacidad con cuidado y en su totalidad, y si está de acuerdo con su contenido, debe crear una cuenta de usuario, con la siguiente casilla de verificación correspondiente a la opción «Acepto la Política», expresando su consentimiento libre, expreso e informado, aceptando y permitiendo el acceso a sus datos a través de la Plataforma. Si no acepta el contenido completo de este Aviso de Privacidad, se abstendrá de utilizar la Plataforma. Se informa a los Usuarios que la Ley establece que el consentimiento del Titular sobre el tratamiento de los Datos Personales se entiende como tácito cuando una vez puesto a su disposición el Aviso de Privacidad, no manifieste oposición alguna.</p>`,
      text: 'En cumplimiento con lo establecido en los artículos 15 y 16 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en adelante, la “Ley”) SUSBANK (en adelante, la “Responsable” o “SUSBANK”) con domicilio en Prado Norte 235 Oficina 13, Lomas de Chapultepec III Sección, Miguel Hidalgo, 11000, Ciudad de México, le informa que el presente Aviso de Privacidad (en adelante, el “Aviso”) está dirigido a los usuarios de SUSBANK (en adelante “Usuario” o “Usuarios.”)El presente documento busca informar a los Usuarios de la plataforma o aplicación móvil de SUSBANK (en adelante, la “Plataforma”), sobre la utilización y tratamiento de la información personal (en adelante, “Datos Personales”) que se recopile o genere a través de las visitas a la Plataforma, así como de los Datos Personales que el Usuario entregue y/o suministre de manera voluntaria a SUSBANK por cualquier medio diverso, o que se generen indirectamente por el uso de la Plataforma. En el primer acceso a la Plataforma, el Usuario debe leer este Aviso de Privacidad con cuidado y en su totalidad, y si está de acuerdo con su contenido, debe crear una cuenta de usuario, con la siguiente casilla de verificación correspondiente a la opción «Acepto la Política», expresando su consentimiento libre, expreso e informado, aceptando y permitiendo el acceso a sus datos a través de la Plataforma. Si no acepta el contenido completo de este Aviso de Privacidad, se abstendrá de utilizar la Plataforma. Se informa a los Usuarios que la Ley establece que el consentimiento del Titular sobre el tratamiento de los Datos Personales se entiende como tácito cuando una vez puesto a su disposición el Aviso de Privacidad, no manifieste oposición alguna.',
      confirmButtonColor: '#343a40',
      confirmButtonText: 'Continuar',
      width:'90%'
    })
  }